# EDA

In [2]:
import pandas as pd

# Users

In [8]:
users = pd.read_csv("../data/users.csv")

In [9]:
users

,user_id,birthdate,gender,married,has_children,home_country,home_city,home_airport,home_airport_lat,home_airport_lon,sign_up_date
0,94883,1972-03-16,F,True,False,usa,kansas city,MCI,39.297,-94.714,2022-02-07
1,101486,1972-12-07,F,True,True,usa,tacoma,TCM,47.138,-122.476,2022-02-17
2,101961,1980-09-14,F,True,False,usa,boston,BOS,42.364,-71.005,2022-02-17
3,106907,1978-11-17,F,True,True,usa,miami,TNT,25.862,-80.897,2022-02-24
4,118043,1972-05-04,F,False,True,usa,los angeles,LAX,33.942,-118.408,2022-03-10
...,...,...,...,...,...,...,...,...,...,...,...
5993,780167,1974-06-08,F,True,True,usa,los angeles,LAX,33.942,-118.408,2023-04-25
5994,785186,1979-06-03,F,True,True,usa,little rock,LIT,34.729,-92.224,2023-04-27
5995,792549,1978-01-25,F,False,False,usa,kansas city,MCI,39.297,-94.714,2023-04-30
5996,811077,1979-02-22,F,True,True,usa,knoxville,TYS,35.812,-83.993,2023-05-06
5997,844489,2000-05-09,M,False,True,usa,el paso,BIF,31.849,-106.380,2023-05-18

In [10]:
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 5998 entries, 0 to 5997
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           5998 non-null   int64
 1   birthdate         5998 non-null   str
 2   gender            5998 non-null   str
 3   married           5998 non-null   bool
 4   has_children      5998 non-null   bool
 5   home_country      5998 non-null   str
 6   home_city         5998 non-null   str
 7   home_airport      5998 non-null   str
 8   home_airport_lat  5998 non-null   float64
 9   home_airport_lon  5998 non-null   float64
 10  sign_up_date      5998 non-null   str
dtypes: bool(2), float64(2), int64(1), str(6)
memory usage: 433.6 KB

No nan values

In [12]:
users.describe()

             user_id  home_airport_lat  home_airport_lon
count    5998.000000       5998.000000       5998.000000
mean   545440.695565         38.439744        -94.176286
std     64924.749760          6.189297         18.071233
min     23557.000000         21.316000       -157.927000
25%    517152.000000         33.818000       -112.383000
50%    540542.000000         39.103000        -90.035000
75%    574146.000000         42.266500        -79.370000
max    844489.000000         61.251000        -63.499000

In [20]:
pd.to_datetime(users["birthdate"], format='%Y-%m-%d', errors='coerce').isnull().sum()

np.int64(0)

In [ ]:
pd.to_datetime(users["sign_up_date"], format='%Y-%m-%d', errors='coerce').isnull().sum()

np.int64(0)

all dates are in the correct format

## Age Analysis

In [23]:
users["birthdate"] = pd.to_datetime(users["birthdate"])

In [25]:
# 2. Today's date
today = pd.Timestamp.now()   # or pd.Timestamp.today()

# 3. Compute age
users["age"] = (today - users["birthdate"]).dt.days // 365

In [26]:
users

,user_id,birthdate,gender,married,has_children,home_country,home_city,home_airport,home_airport_lat,home_airport_lon,sign_up_date,age
0,94883,1972-03-16,F,True,False,usa,kansas city,MCI,39.297,-94.714,2022-02-07,54
1,101486,1972-12-07,F,True,True,usa,tacoma,TCM,47.138,-122.476,2022-02-17,53
2,101961,1980-09-14,F,True,False,usa,boston,BOS,42.364,-71.005,2022-02-17,46
3,106907,1978-11-17,F,True,True,usa,miami,TNT,25.862,-80.897,2022-02-24,47
4,118043,1972-05-04,F,False,True,usa,los angeles,LAX,33.942,-118.408,2022-03-10,54
...,...,...,...,...,...,...,...,...,...,...,...,...
5993,780167,1974-06-08,F,True,True,usa,los angeles,LAX,33.942,-118.408,2023-04-25,52
5994,785186,1979-06-03,F,True,True,usa,little rock,LIT,34.729,-92.224,2023-04-27,47
5995,792549,1978-01-25,F,False,False,usa,kansas city,MCI,39.297,-94.714,2023-04-30,48
5996,811077,1979-02-22,F,True,True,usa,knoxville,TYS,35.812,-83.993,2023-05-06,47
5997,844489,2000-05-09,M,False,True,usa,el paso,BIF,31.849,-106.380,2023-05-18,26

In [29]:
users["age"].plot(kind="hist")

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

# Gender Analysis